export const config = {
    title_before_outline: 'QUICK',
    title_outline: 'NFT AUCTIONS',
    title_after_outline: 'ON YOUR DEVICE',
    section_1_title_before_outline: 'top nft of',
    section_1_title_outline: 'month',
    section_1_title_after_outline: '',
    section_2_title_before_outline: '',
    section_2_title_outline: 'create and sell',
    section_2_title_after_outline: 'your nfts',
    section_3_title_before_outline: 'store',
    section_3_title_outline: '',
    section_3_title_after_outline: '',
    section_4_title_before_outline: 'popular nft',
    section_4_title_outline: 'collections',
    section_4_title_after_outline: '',
    section_5_title_before_outline: '',
    section_5_title_outline: 'what people say',
    section_5_title_after_outline: 'about us',
    footer_phone_number: '+00000000000',
    footer_email: 'exampe@gmail.com',
    footer_address: 'st. Example, 8',

    primaryColor: '#7E76DA',
    secondaryColor: '#31354D',
    darkTextColor: '#000000',
    lightTextColor: '#ffffff',

    gradient_color_1: '#F88C8C',
    gradient_color_2: '#5795CA',
    gradient_color_3: '#57CAB9',

    search_gradient_color_1: '#f09',
    search_gradient_color_2: '#0ff',
    search_gradient_color_3: '#9f0',

    stepper_icon_gradient_color_1: '#f09',
    stepper_icon_gradient_color_2: '#0ff',
    stepper_icon_color: '#fff',
}